apiVersion: v1
kind: Service
metadata:
  name: smartlighting-backend-service
spec:
  selector:
    app: smartlighting-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31216
  type: NodePort 