apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartlighting-backend
  labels:
    app: smartlighting-backend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: smartlighting-backend
  template:
    metadata:
      labels:
        app: smartlighting-backend
    spec:
      containers:
      - name: smartlighting-backend
        image: nginx:alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 3 