apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-fastapi
  labels:
    app: basic-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-fastapi
  template:
    metadata:
      labels:
        app: basic-fastapi
    spec:
      containers:
      - name: fastapi
        image: python:3.11-slim
        command: ["/bin/sh", "-c"]
        args:
        - |
          pip install fastapi uvicorn
          cat > /tmp/simple_app.py << 'EOF'
          from fastapi import FastAPI
          import time
          import math
          import random
          import socket
          from datetime import datetime
          
          app = FastAPI()
          request_count = 0
          
          @app.get("/")
          def root():
              global request_count
              request_count += 1
              return {
                  "message": "Basic FastAPI Test",
                  "hostname": socket.gethostname(),
                  "request_count": request_count,
                  "timestamp": datetime.now().isoformat()
              }
          
          @app.get("/health")
          def health():
              return {"status": "healthy"}
          
          @app.get("/load")
          def create_load():
              global request_count
              request_count += 1
              # Створює навантаження на CPU
              result = 0
              for i in range(100000):
                  result += math.sqrt(i * random.random())
              return {
                  "message": "Load test completed",
                  "hostname": socket.gethostname(),
                  "result": result,
                  "request_count": request_count
              }
          EOF
          cd /tmp
          python -m uvicorn simple_app:app --host 0.0.0.0 --port 8000
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: basic-fastapi-service
spec:
  selector:
    app: basic-fastapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 32300
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: basic-fastapi-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: basic-fastapi
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 